### PR TITLE
Bug: Update existing assets and only set hooks once.

### LINKED ISSUE #59: Bug: webpack --watch adds "stats.json" to output causing "multiple assets emit different content to the same filename" error.
If I initialize the plugin with a custom `fields` list - eg:

```js
new StatsWriterPlugin({
    fields: ["assetsByChunkName", "assets", "entrypoints"],
  })
```

and run `webpack --watch`, each time assets are changed, I see this warning in the output:

```
WARNING in Conflict: Multiple assets emit different content to the same filename stats.json
```

This only started in the 1.0.x releases - 0.3.2 doesn't display the same problem.

There's a demo repo here: https://github.com/jdelStrother/webpack-stats-test

### PR DESCRIPTION
**Pull request by ryan-roemer**
* Only call `compiler.hooks.emit.tapPromise("stats-writer-plugin")` once for legacy mode hooks. Fixes #59 
* Check if asset exists and either emits or updates accordingly.

@evilebottnawi -- Thanks for your guidance again! Mind seeing if my `once()` wrapper to only set hooks once after capturing `thisCompilation` works? I noticed this avoids the situation of the stats file _itself_ ending up in the `compilation` which is what I think we want, but would love a second opinion!

@jdelStrother -- Mind giving this branch a whirl and see if it fixes your problem and otherwise behaves like you would expect?

### CODE REVIEW

File: lib/stats-writer-plugin.js [hunk 1]
```diff
@@ -3,6 +3,17 @@
...
+// Helper to call a function only once.
+const once = function (fn) {
+  let called = false;
+  return (...args) => {
+    if (!called) {
+      called = true;
+      fn(...args);
+    }
+  };
+};
```
Comment (evilebottnawi) [inline lib/stats-writer-plugin.js:15]: It will break watch mode for your plugin

Comment (ryan-roemer) [reply lib/stats-writer-plugin.js:15]: Can you help explain this a little more to me? I am using this with the sample repository that @jdelStrother  provided and specifically in testing watch mode which now appears to work correctly.

Without this change, I see multiple invocations of the hooks on every watch change. They add up on each file change and it seems like the wrong thing is happening.

**Comment by jdelStrother** [comment]
For what it's worth, seems like it's working as expected for me.

File: lib/stats-writer-plugin.js (hunk 1 above)
Comment (evilebottnawi) [reply lib/stats-writer-plugin.js:15]: It is expected, because developer can remove `dist` directory on each run, **never** use `once` for hooks

Comment (ryan-roemer) [reply lib/stats-writer-plugin.js:15]: To explain what I'm seeing a little more, here's what is happening right now in watch mode with current published 1.0.1 version of the plugin in watch mode in https://github.com/jdelStrother/webpack-stats-test repository:

Initial start:

- outer `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` fires
- nested `compilation.hooks.processAssets.tapPromise()` fires

File change #1:

- outer `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` fires
- nested `compilation.hooks.processAssets.tapPromise()` fires
- nested `compilation.hooks.processAssets.tapPromise()` fires

File change #2:

- outer `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` fires
- nested `compilation.hooks.processAssets.tapPromise()` fires
- nested `compilation.hooks.processAssets.tapPromise()` fires
- nested `compilation.hooks.processAssets.tapPromise()` fires

... and so on. 

The reason we get the original `multiple assets emit different content to the same filename` warning in https://github.com/FormidableLabs/webpack-stats-plugin/issues/59 is because I think of this issue and not anything more (which means the `updateAsset()` tweak is more just a nicety than actual core issue solution.)

What my read is that we only need `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` to fire **once** because I need to capture the `compilation` object to manually pass into `compilation.hooks.processAssets` later where it otherwise wouldn't be available.

With the changes in this PR, this it the new behavior:

Initial start:

- outer `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` fires
- nested `compilation.hooks.processAssets.tapPromise()` fires

File change #1:

- nested `compilation.hooks.processAssets.tapPromise()` fires

File change #2:

- nested `compilation.hooks.processAssets.tapPromise()` fires

... and so on. The original `compilation` object captured in initial start is passed to the function in `compilation.hooks.processAssets`.

Does that make sense or is there some reason why we can't capture the `compilation` object initially in `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` and not recapture after?

What I'm thinking if there is some need to update the `compilation` object is to do it in a way that separates `compilation.hooks.processAssets.tapPromise()` from `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` so that `compilation.hooks.processAssets.tapPromise()` continues to only be called once during a straight `webpack` build or during a single file change in `webpack --watch`.

Comment (ryan-roemer) [reply lib/stats-writer-plugin.js:15]: Ah, I tried out @jdelStrother's repo with webpack 5 and I am seeing an issue where further hooks aren't updated, which is probably related to `compilation` object. I'm investigating further...

Comment (evilebottnawi) [reply lib/stats-writer-plugin.js:15]: just note - https://github.com/FormidableLabs/webpack-stats-plugin/blob/dc4336389d002dc1a17c6b446d84ede13b1586c4/lib/stats-writer-plugin.js#L101 you need to return promise here, because you use `tapPromise`

**Comment by ryan-roemer** [comment]
Thanks for the feedback @jdelStrother !

@evilebottnawi -- I refactored to https://github.com/FormidableLabs/webpack-stats-plugin/pull/60/commits/2333775c2ba082373883f62c4fbd7dd9a98f26ed and I think I've got the right thing now, which is:

1. In modern mode, call `compiler.hooks.thisCompilation.tap("stats-writer-plugin")` and set `compilation.hooks.processAssets.tapPromise()` repeatedly in watch mode.
2. In legacy mode if `compilation.hooks.processAssets` is not available, only set `compiler.hooks.emit.tapPromise("stats-writer-plugin")` once.

Switching back and forth between webpack4 and webpack5 in https://github.com/jdelStrother/webpack-stats-test this seems to work in both cases now. Does that seem right?

Thanks for all the help!

File: lib/stats-writer-plugin.js (hunk 1 above)
Comment (ryan-roemer) [reply lib/stats-writer-plugin.js]: Thanks for the note! `emitStats()` returns a promise.

**Comment by evilebottnawi** [comment]
> Switching back and forth between webpack4 and webpack5 in https://github.com/jdelStrother/webpack-stats-test this seems to work in both cases now. Does that seem right?

yes, it is right, you can add tests for this to avoid future regressions, if you use `jest` you can use `jest.spyOn` to test it

**Comment by ryan-roemer** [comment]
Great testing suggestion @evilebottnawi (I use mocha + sinon, but same thing). I've added https://github.com/FormidableLabs/webpack-stats-plugin/issues/61 for myself to add in-memory webpack-invoking tests to poke things like watch mode.

Currently the test infrastructure is more "end to end"-ish which just invokes full `webpack` processes and then examines builds -- I can't do `webpack --watch` there because the tests would get hung up and I'm not in the same process for spying...

**Comment by ryan-roemer** [comment]
Released in `webpack-stats-plugin@1.0.2`
